version: '3.8'
services:
  predis:
    image: redis:6.0.5-alpine
    restart: always

  redis:
    image: redis:6.0.5-alpine
    restart: always

  server:
    image: cord-server
    command: bash -c 'npm i sharp && ./run-server.sh'
    build:
      context: .
      dockerfile: ./ops/dockerfiles/server.Dockerfile
    environment:
      - CORD_TIER=prod
    volumes:
      - $HOME/.aws:/root/.aws:ro
    depends_on:
      - redis
      - predis
    restart: always
    ports:
      - '8101:8101'
      - '8111:8111'
      - '8123:8123'
      - '8161:8161'
      - '8171:8171'

  worker:
    image: cord-server
    command: bash -c 'npm i sharp && npm run start-asyncWorker-prod'
    environment:
      - CORD_TIER=prod
    volumes:
      - $HOME/.aws:/root/.aws:ro
    depends_on:
      - server
    restart: always
